# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Diogo L. Pires
tagline:          'Diogo L. Pires'
description:      ''
url:              https://diogolpires.github.io
baseurl:          /

author:
  name:           'Diogo L. Pires'
  url:            https://twitter.com/pires_dl

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/diogolpires/diogolpires.github.io
