# Setup
title:            Diogo L. Pires
tagline:          'Personal page'
description:      'PhD candidate <a href="https://www.city.ac.uk/about/people/academics/diogo-pires#" target="_blank">@CityUniLondon</a> and Marie Curie Fellow <a href="https://evogamesplus.eu" target="_blank">@EvoGamesPlus</a>.'
url:              https://diogolpires.github.io
#baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Diogo Pires'
  url:            https://twitter.com/pires_dl

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          1.0.0
