# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Diogo L. Pires
tagline:          'Personal Website'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme.'
url: "https://diogolpires.github.io"
baseurl: ""

author:
  name:           'Diogo L. Pires'
  url:            https://twitter.com/pires_dl

paginate:         5

# Custom vars
version:         1.

github:
  repo:           https://github.com/diogolpires/diogolpires.github.io
